name: BlockDescription
version: '${project.version}'
main: ru.permasha.blockdescription.Main
api-version: 1.19
softdepend: [HolographicDisplays]
commands:
  blockdesc:
    description: Add attribute of block
